// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqgsbpzowmzvfejxfdyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZ3NicHpvd216dmZlanhmZHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDYxOTUsImV4cCI6MjA2OTI4MjE5NX0.MXTyOoBUR4bzwoVcsaluDio3fh66LmAaaG0A68f_7kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});